Assignment-2: Event handling & DOM
vaibhav-webonise/JavaScript-Assignments pull request #2
Opened 2019-09-30 13:49 UTC by vaibhav-webonise

**Problem 1:** Write a JavaScript code that starts to execute on a button click and will open a particular url in multiple new tabs (say 5) and close them after a certain interval recursively. The script should stop its execution onclick of another button on the same page.

**Problem 2:** Create a simple form that will accept name and email of a user and onsubmit, stores the details with the current timestamp. User can add multiple name and email sets. There should  be a button “SHOW USERS” which will list all the name and email sets with their timestamp in the document. Form should be validated before submission else it should show an error. (Expected session handling for this)

2019-10-01 06:47 UTC, swapnil-webonise requested changes

2019-10-01 06:47 UTC, swapnil-webonise commented on EventHandlingDemo.html
> +<!DOCTYPE html>
Again same thing repeated here, Indentation improper

2019-10-01 06:47 UTC, swapnil-webonise commented on ValidateUser.html
> +        let userName = document.getElementById("nameOfUser").value;
Use single quotes

2019-10-01 06:47 UTC, swapnil-webonise commented on ValidateUser.html
> +            document.write("<b>User Name :</b> " + userName);
Use template string for concatenation

2019-10-01 09:39 UTC, vaibhav-webonise commented on EventHandlingDemo.html
> +<!DOCTYPE html>
that one line after body and button tag or anything else in the file?

2019-10-03 06:56 UTC, swapnil-webonise commented on EventHandlingDemo.html
> +<!DOCTYPE html>
everything should be indented with 2 space tab

2019-10-04 08:42 UTC, swapnil-webonise approved these changes

2019-10-04 08:43 UTC, merged