Assignment-4: Promises in JavaScript
vaibhav-webonise/JavaScript-Assignments pull request #4
Opened 2019-10-03 14:30 UTC by vaibhav-webonise

**problem 1:** Addition using promise
**problem 2:** Division using promise

2019-10-04 05:17 UTC, deepakb-webonise commented on AdditionPromise.html
> +        <meta charset="UTF-8">
The assignment looks good. try to use the fat arrow functions

2019-10-04 05:17 UTC, deepakb-webonise commented on AdditionPromise.html
> +                let additionResult = addTwoNumbers(numberOne,numberTwo);
no need additionResult variable we can directly then on function.

2019-10-04 05:17 UTC, deepakb-webonise commented on DivisionPromise.html
> +        <script>
The assignment looks good. checkout the previous assignment comments same applies here

2019-10-04 05:17 UTC, deepakb-webonise approved these changes

2019-10-07 12:28 UTC, swapnil-webonise requested changes

2019-10-07 12:28 UTC, swapnil-webonise commented on DivisionPromise.html
> +                let numberOne = parseInt(document.getElementById('numberOne').value);
Prefer `const` over `let`, as we are not modifying a value further

2019-10-07 12:28 UTC, swapnil-webonise commented on DivisionPromise.html
> +                let numberOne = parseInt(document.getElementById('numberOne').value);
Check this across PR

2019-10-07 12:28 UTC, swapnil-webonise commented on PrintNumbersbyPromise.html
> +            function displayNumbers(number) {
Give linebreak between two functions

2019-10-07 13:14 UTC, swapnil-webonise approved these changes

2019-10-07 13:14 UTC, merged